/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SecondaryButton {
        "text": string;
    }
    interface TestButton {
        "name": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSecondaryButtonElement extends Components.SecondaryButton, HTMLStencilElement {
    }
    var HTMLSecondaryButtonElement: {
        prototype: HTMLSecondaryButtonElement;
        new (): HTMLSecondaryButtonElement;
    };
    interface HTMLTestButtonElement extends Components.TestButton, HTMLStencilElement {
    }
    var HTMLTestButtonElement: {
        prototype: HTMLTestButtonElement;
        new (): HTMLTestButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "secondary-button": HTMLSecondaryButtonElement;
        "test-button": HTMLTestButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SecondaryButton {
        "text"?: string;
    }
    interface TestButton {
        "name"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "secondary-button": SecondaryButton;
        "test-button": TestButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "secondary-button": LocalJSX.SecondaryButton & JSXBase.HTMLAttributes<HTMLSecondaryButtonElement>;
            "test-button": LocalJSX.TestButton & JSXBase.HTMLAttributes<HTMLTestButtonElement>;
        }
    }
}
